# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# Optional: Set environment variables if needed
# ENV MONGO_INITDB_ROOT_USERNAME=myusername
# ENV MONGO_INITDB_ROOT_PASSWORD=mypassword

# Optional: Copy any additional configuration files or scripts
# COPY myconfigfile.js /docker-entrypoint-initdb.d/
